defmodule BirdsAgainstMortalityWeb.Plugs.User do
  import Plug.Conn

  def init(default), do: default

  def call(%Plug.Conn{params: %{"new_name" => newName}} = conn, _opts) do
      existingUser = get_session(conn, :user)

      if is_nil(existingUser) do
        conn
        |> put_session(:user, %{id: UUID.uuid1(), name: newName, color: get_color()})
      else
        newConn = conn
        |> put_session(:user, %{existingUser | name: newName})

        IO.inspect(get_session(newConn, :user))
        newConn
      end
  end
  def call(conn, _default) do
    if is_nil(get_session(conn, :user)) do
      conn
      |> put_session(:user, %{id: UUID.uuid1(), name: get_name(), color: get_color()})
    else
      conn
    end
  end

  def get_color() do
    :random.seed(:erlang.now)
    colors = ["red", "orange", "yellow", "olive", "green", "teal", "blue", "violet", "purple", "pink"]
    Enum.random(colors)
  end
  def get_name() do
    :random.seed(:erlang.now)
    names = [
      "Dislike Robot",
      "Mail Leash",
      "Hnads Dog",
      "Android Horse",
      "Cone Floppy Disk",
      "Boat Plus",
      "System Monster",
      "Monster Website",
      "Breakfast Dislike",
      "Laptop Dislike",
      "Toilet Toilet",
      "Leash Cone",
      "Running Comics",
      "Running Urine",
      "Comics Ice cream cone",
      "Prints Website",
      "Flowers Laptop",
      "Shower Comics",
      "Book Ice cream",
      "Ice cream Towel",
      "Soap Ice cream",
      "Prints Rollers",
      "Drugs Robot",
      "Nuclear Male",
      "Leash Mail",
      "Whale Shoes",
      "Shoe Bird",
      "Horse Soda",
      "Allergies Shelf",
      "Clock Towel",
      "Robot Ice cream cone",
      "Soda Fusion",
      "Laptop Hnads",
      "Clock Plus",
      "Cone System",
      "Shelf Cone",
      "System BBQ",
      "Fence Hnads",
      "Trees Shelf",
      "Water Leash",
      "Male Flowers",
      "Solar Drugs",
      "Kitty YouTube",
      "Soap Dislike",
      "Sink Poop",
      "Toolbox Boat",
      "Urine Laptop",
      "Horse Shoes",
      "Running Shoes",
      "Bird Prints",
      "Monster Settings",
      "Shoes Body",
      "Elevator Sink",
      "Flowers Book",
      "Leash Floppy Disk",
      "Soda Ice cream cone",
      "Cone Bird",
      "Robot Post office",
      "Flowers Dog",
      "YouTube Allergies",
      "System Body",
      "Puppy Sink",
      "Hnads Shelf",
      "Shoe Whale",
      "Laptop Toilet",
      "Shower Video games",
      "Post office Prints",
      "Prints Clock",
      "Horse Shoe",
      "Shelf Leash",
      "Soap Trees",
      "Soda Urine",
      "Shoe Kitty",
      "Towel Shower",
      "Floppy Disk Urine",
      "Toilet Prints",
      "Clock Running",
      "Leash Sink",
      "Kitty Ring",
      "Ice cream Monster",
      "Light saber Ring",
      "Trees Fence",
      "Nuclear Urine",
      "Boat Allergies",
      "Post office Towel",
      "Printer Websites",
      "BBQ Leash",
      "Fence Dog",
      "Toilet Soda",
      "Trees Settings",
      "Ring Shower",
      "Drugs Dislike",
      "Android BBQ",
      "Post office Poop",
      "Dog Websites",
      "Printer Running",
      "Monster Body",
      "Water Android",
      "Bird Prints",
      "Poop Websites",
      "Plants Leash",
      "Shoe YouTube",
      "Dislike Book",
      "Plants Poop",
      "Clock Ring",
      "Sink Book",
      "Breakfast Video games",
      "Video games Rollers",
      "Shower Plants",
      "Hnads Book",
      "Dog Comics",
      "Ice cream Fusion",
      "Video games Dislike",
      "Android Whale",
      "Nuclear Settings",
      "Shoes Light saber",
      "Bird Post office",
      "Ice cream Clock",
      "Shoe Websites",
      "Post office Hnads",
      "BBQ Whale",
      "Puppy Nuclear",
      "Rollers Book",
      "Cat Ice cream",
      "Shoes BBQ",
      "Plants Plus",
      "Floppy Disk Allergies",
      "Cone Video games",
      "Fence Soap",
      "Boat Cone",
      "Plants YouTube",
      "Sink Robot",
      "BBQ Dog",
      "Body Whale",
      "Plants Shoes",
      "Android Flowers",
      "Whale Book",
      "Trees Cone",
      "Toilet Cone",
      "Websites Dog",
      "Fusion Male",
      "Ice cream Ring",
      "Plants Solar",
      "Water Robot",
      "Comics Solar",
      "Running Puppy",
      "Soda YouTube",
      "Toilet Running",
      "YouTube Android",
      "Shower Allergies",
      "Whale Robot",
      "Ring Clock",
      "Whale Urine",
      "Ice cream Video games",
      "Toolbox Poop",
      "Printer Dislike",
      "Dog Water",
      "Dog Body",
      "Monster Comics",
      "Elevator Video games",
      "Allergies Soap",
      "Toilet Comics",
      "Flowers Settings",
      "Android Solar",
      "Monster Bird",
      "Shelf Cone",
      "Water Towel",
      "Toolbox Cone",
      "Whale Ice cream",
      "Fence Shoe",
      "Light saber Floppy Disk",
      "Sink Cat",
      "YouTube Water",
      "Horse Printer",
      "Shelf Running",
      "Boat Whale",
      "Toilet Drugs",
      "Urine Puppy",
      "YouTube Water",
      "Rollers Shoe",
      "Fence Towel",
      "Websites Towel",
      "Shower Comics",
      "Dog Laptop",
      "Ice cream cone Whale",
      "BBQ Website",
      "Comics Plus",
      "Running Body",
      "Leash Solar",
      "Soap Printer",
      "Urine Flowers",
      "Sink Floppy Disk",
      "Light saber Water",
      "Horse Monster",
      "Rollers Dog",
      "Light saber Dislike",
      "Book Shelf",
      "Toilet Plus",
      "Dog YouTube",
      "Breakfast System",
      "Website Flowers",
      "Urine Toolbox",
      "Fusion YouTube",
      "Crab Elevator",
      "Breakfast Horse",
      "Whale Dislike",
      "Poop Poop",
      "Floppy Disk Urine",
      "Solar Mail",
      "Trees Nuclear",
      "Whale Horse",
      "Printer Dislike",
      "Body Toolbox",
      "Soda Light saber",
      "Allergies Settings",
      "Toolbox Breakfast",
      "Robot Running",
      "Whale Comics",
      "Book Dislike",
      "Water Post office",
      "YouTube Plants",
      "Soap Cone",
      "Floppy Disk Website",
      "Water Soda",
      "Book Websites",
      "Soda Solar",
      "Comics Clock",
      "Cat Elevator",
      "Body Fence",
      "Comics Cat",
      "Towel Nuclear",
      "Allergies Cat",
      "Urine Clock",
      "Post office Solar",
      "System Dog",
      "Book Poop",
      "Ice cream Website",
      "Shower Mail",
      "BBQ Whale",
      "Drugs Drugs",
      "Towel Websites",
      "Horse Trees",
      "Boat Post office",
      "Urine Ring",
      "Cat Video games",
      "Running Male",
      "Book Breakfast",
      "Crab Shoe",
      "Boat Toolbox",
      "Video games Solar",
      "Fence Shoe",
      "Soap Android",
      "Drugs Ice cream cone",
      "Body Dog",
      "Plants Nuclear",
      "Prints Mail",
      "Dislike Post office",
      "Shoes Drugs",
      "Video games Male",
      "Male Robot",
      "Kitty Rollers",
      "Solar Post office",
      "Dog Elevator",
      "Horse Sink",
      "Water Soap",
      "Shoe Clock",
      "Dislike Shoe",
      "Shelf Ring",
      "Shelf Video games",
      "Plus Water",
      "Body Elevator",
      "Floppy Disk Soda",
      "Allergies Cat",
      "Ice cream cone Puppy",
      "YouTube Male",
      "Soda Shoes",
      "Hnads Light saber",
      "Running Rollers",
      "Prints Flowers",
      "Sink Boat",
      "Floppy Disk Body",
      "Rollers Kitty",
      "Boat Breakfast",
      "Towel Whale",
      "Soap Ring",
      "Comics Cat",
      "Trees Kitty",
      "Water Monster",
      "Breakfast Rollers",
      "Robot Toilet",
      "Male Fusion",
      "Light saber Dislike",
      "Trees Ice cream",
      "Shelf Urine",
      "Male Robot",
      "Hnads Flowers",
      "Video games Dislike",
      "Cat Whale",
      "Shoe Hnads",
      "Trees Shoe",
      "Laptop Allergies",
      "Post office Drugs",
      "YouTube Websites",
      "Breakfast Kitty",
      "Shower Android",
      "Body Monster",
      "Running Laptop",
      "Kitty Mail",
      "Horse Kitty",
      "Soda Hnads",
      "Poop Fence",
      "YouTube Robot",
      "Ice cream Floppy Disk",
      "Bird Fence",
      "Cat Body",
      "Male Light saber",
      "Toolbox System",
      "Drugs Ice cream cone",
      "Rollers Cat",
      "Hnads Light saber",
      "Crab Boat",
      "BBQ Mail",
      "Shoe Urine",
      "Plus Male",
      "Floppy Disk Poop",
      "Male Boat",
      "Android Trees",
      "Rollers Nuclear",
      "Soap Ice cream cone",
      "Shoe Monster",
      "Trees YouTube",
      "Ice cream cone Nuclear",
      "Plus Urine",
      "BBQ Kitty",
      "Plants Poop",
      "BBQ Breakfast",
      "Urine Sink",
      "Floppy Disk Body",
      "System Towel",
      "Whale Dislike",
      "Horse Body",
      "Floppy Disk Trees",
      "Toilet Settings",
      "Dislike YouTube",
      "Mail Ice cream",
      "Clock Trees",
      "Fence Puppy",
      "Crab Cone",
      "Ring Kitty",
      "Running Kitty",
      "Comics Male",
      "Boat Settings",
      "Toolbox Leash",
      "Website Drugs",
      "Poop Book",
      "Book Crab",
      "BBQ Shower",
      "Floppy Disk Comics",
      "Running Bird",
      "Plants Male",
      "Dog Post office",
      "Ice cream Body",
      "Dislike BBQ",
      "Whale Ice cream cone",
      "Flowers Plants",
      "Fence Shoes",
      "Monster Hnads",
      "Monster Android",
      "Solar Toolbox",
      "Flowers Mail",
      "Shelf Breakfast",
      "Laptop Body",
      "Laptop Solar",
      "Fusion Flowers",
      "Water Shoes",
      "Horse Allergies",
      "Leash Elevator",
      "Prints Website",
      "Toilet Toilet",
      "Monster Hnads",
      "Kitty Trees",
      "Plants Kitty",
      "Male Dislike",
      "Soap Video games",
      "Breakfast Toolbox",
      "Urine Trees",
      "Plants Sink",
      "Printer BBQ",
      "Kitty Clock",
      "Settings Settings",
      "Websites Toolbox",
      "Printer Ice cream cone",
      "Toilet Boat",
      "Dog Fence",
      "Prints Settings",
      "Shower Ring",
      "Poop Elevator",
      "Puppy Shoes",
      "Kitty Poop",
      "Clock Clock",
      ]

      Enum.random(names)
    end
end
